project:
  type: website
  render:
    - "*.md"
    - "*.qmd"

website:
  repo-url: https://github.com/pvgenuchten/training-gitops-sdi/
  repo-actions:
    - edit
    - issue
  page-footer:
    left:
    - text: "@pvgenuchten 2025"
      file: https://pvgenuchten.github.io/training-gitops-sdi/
  title: ""
  search: false
  navbar:
    pinned: true
    right:
      - text: Home
        file: "./index.md"
      - text: Slides
        file: "./slides/index.qmd"
  sidebar:
    - search: true
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - text: Home
          file: index.md
        - text: Existing resources
          file: 1-metadata-at-the-source.md
        - text: Data repositories
          file: 2-interact-with-data-repositories.md
        - text: Catalogue publication
          file: 3-catalogue-publication.md
        - text: Bulk import
          file: 4-bulk-import.md
        - text: Git actions
          file: 5-git-cicd.md
        - text: Data publication
          file: 6-data-publication.md
        - text: Map services
          file: 7-providing-map-services.md
        - text: Data visualisation
          file: 8-data-visualisation.md


